# version: '3.7'
# volumes:
#   data:
# services:
#   db:
#     image: mysql:latest
#     ports:
#       - "3306:3306"
#     restart: always
#     volumes:
#       - data:/var/lib/mysql
#     environment:
#       - MYSQL_ROOT_PASSWORD="123456"
#       - MYSQL_DATABASE="projetofinaldb"
#     networks:
#       - mysql-compose-network
#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080
#     depends_on: 
#       - db
# networks: 
#   mysql-compose-network:
#     driver: bridge

  # app:
  #   image: phpmyadmin/phpmyadmin:latest
  #   container_name: phpmyadmin
  #   links:
  #     - db
  #   ports:
  #     - 80:80
  #   environment:
  #     - PMA_ARBITRARY=1

# version: '3'

# services:
#   mysqlsrv:
#     image: mysql:5.7
#     command: --default-authentication-plugin=mysql_native_password
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: "password"
#       MYSQL_DATABASE: "testedb"
#     ports:
#       - "3306:3306"
#     volumes:
#       - /home/renatogroffe/Desenvolvimento/Docker/Volumes/MySql:/var/lib/mysql
#     networks:
#       - mysql-compose-network

#   adminer:
#     image: adminer
#     ports:
#       - 8080:8080
#     networks:
#       - mysql-compose-network

# networks: 
#   mysql-compose-network:
#     driver: bridge

version: '3.7'
services:
  db:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password    
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: "db"
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on: 
      - db