version: '3.7'
services:
  db:
    image: mysql:latest #5.7
    volumes: 
      - ./.docker/mysql/data:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    restart: always
    command: --default-authentication-plugin=mysql_native_password    
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "projetofinaldb"
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on: 
      - db

  app:
    image: openjdk:8-jdk-alpine
    ports:
    - "8080:8080"
    restart: always
    volumes:
    - .:/app
    working_dir: /app
    command: ./mvnw spring-boot:run 
    depends_on:
      - db