version: '3.7'
services:
  db:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password    
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: "db"
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on: 
      - db